services:
  neo4j:
    image: neo4j:ubi9
    ports:
      - "7474:7474" # Web interface
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword123
    volumes:
      - ./data/neo4j:/data

  ollama:
    image: ollama/ollama:0.23.1
    ports:
      - "11434:11434"
    volumes:
      - ./data/ollama:/root/.ollama
    entrypoint: >
      /bin/sh -c "
        ollama serve &
        until ollama list; do sleep 2; done;
        ollama pull llama3.1;
        ollama pull nomic-embed-text;
        wait
        "

  python-app:
    build: .
    depends_on:
      - neo4j
      - ollama
    ports:
      - "8000:8000"
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    volumes:
      - .:/app
