services:
  neo4j:
    image: neo4j:ubi9
    ports:
      - "7474:7474" # Web interface
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/testpassword123
    volumes:
      - ./backend/data/neo4j:/data

  python-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    depends_on:
      - neo4j
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - .env
    volumes:
      - ./backend:/app

  angular-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - python-app
